-- Adult-provisioned credential accounts (username + password, no email/OAuth).
-- An authenticated adult (teacher/creator) provisions a child/student user who
-- signs in with an autogenerated login + password. On login the platform mints
-- the normal PAS session JWT, so the account is a first-class PAS identity.
-- See routes/auth.ts (credentials/provision + credentials/login). Driven by
-- chess-academy (students are children with no email). COPPA-friendly: the
-- funny-animal login is the privacy feature — no email, no required real name.

ALTER TABLE users ADD COLUMN credential_login TEXT;   -- username, e.g. "rabbit-bear-wolf"
ALTER TABLE users ADD COLUMN password_hash    TEXT;   -- PBKDF2-SHA256: "pbkdf2$<iter>$<saltB64>$<hashB64>"
ALTER TABLE users ADD COLUMN is_child         INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN created_by        TEXT;  -- uid of the provisioning adult

-- One login per account. Partial index so the existing OAuth rows (NULL login)
-- don't collide and don't bloat the index.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_credential_login
  ON users(credential_login) WHERE credential_login IS NOT NULL;

-- Fixed-window failed-attempt counter for credentials/login rate limiting.
-- One row per login; reset on success, windowed reset on expiry. See
-- lib/credential-rate-limit.ts.
CREATE TABLE IF NOT EXISTS credential_login_attempts (
  login        TEXT    PRIMARY KEY,
  window_start INTEGER NOT NULL,   -- epoch ms the current window opened
  count        INTEGER NOT NULL    -- failed attempts in the current window
);
