/** Safe remote MCP approval broker (#355). v1 remains withdrawn; v2 never returns a PAS session. */
import { Hono } from 'hono';
import { deleteCookie, getCookie, setCookie } from 'hono/cookie';
import { verifySession } from '@proappstore/build-core';
import { requireUser } from '../lib/auth.js';
import { BROKER_LOGIN_CODE_COOKIE, redeemExchangeCode } from './auth.js';
import type { Env } from '../types.js';

export const mcpBrokerRoutes = new Hono<{ Bindings: Env }>();
export const MCP_BROKER_VERSION = '2026-10-10';
const V1 = '/mcp/broker/v1'; const PREFIX = '/mcp/broker/v2';
const HTTP_PREFIX = `/v1${PREFIX}`;
const TTL = 10 * 60_000; const RESULT_TTL = 5 * 60_000; const POLL_MS = 2_000;
const APPROVAL_COOKIE = '__Secure-pas_broker_approval';
const requestIdRe = /^req_[A-Za-z0-9_-]{43}$/; const hashRe = /^[a-f0-9]{64}$/;
const challengeRe = /^[A-Za-z0-9_-]{43,128}$/; const identityRe = /^[A-Za-z0-9._:-]{1,120}$/;
const labelRe = /^[\x20-\x7e]{1,120}$/;
type Status = 'pending'|'approving'|'approved_awaiting_machine'|'consumed'|'connected'|'denied'|'expired'|'cancelled'|'failed';
interface Row { request_id:string; owner_id:string; agent_id:string; agent_label:string; machine_id:string; machine_label:string; resource:string; scopes:string; code_challenge:string; machine_proof_hash:string; machine_public_key:string|null; status:Status; expires_at:number; result_iv:string|null; result_ciphertext:string|null; result_expires_at:number|null; redeem_attempt_id:string|null; last_poll_at:number|null; terminal_at:number|null; }
interface Approval { requestId:string; session:string; expiresAt:number; }

const secure = (headers: Record<string,string> = {}) => ({ 'Cache-Control':'no-store', 'Referrer-Policy':'no-referrer', ...headers });
const unavailable = (c:any, status=409) => c.json({ error:'remote_auth_unavailable', protocol_version:MCP_BROKER_VERSION }, status, secure());
const invalid = (c:any) => c.json({ error:'invalid_remote_auth_request', protocol_version:MCP_BROKER_VERSION }, 400, secure());
const withdrawn = (c:any) => unavailable(c, 503);
function b64(bytes:Uint8Array) { let s=''; for (const b of bytes) s += String.fromCharCode(b); return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
function unb64(value:string) { const padded=value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4); return Uint8Array.from(atob(padded), c=>c.charCodeAt(0)); }
function randomId() { return `req_${b64(crypto.getRandomValues(new Uint8Array(32)))}`; }
function printable(value:unknown, max=120):string|null { return typeof value==='string' && value.length<=max && labelRe.test(value) ? value : null; }
function escape(value:string) { return value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]!); }
function timingSafeEqual(left:string,right:string) { if(left.length!==right.length)return false; let different=0; for(let i=0;i<left.length;i+=1)different|=left.charCodeAt(i)^right.charCodeAt(i); return different===0; }
async function sha(value:string) { const digest=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))); return [...digest].map(x=>x.toString(16).padStart(2,'0')).join(''); }
function resource(value:unknown, origin:string|undefined):string|null { if(typeof value!=='string'||!origin)return null; try { const u=new URL(value), o=new URL(origin); if(u.origin!==o.origin||u.search||u.hash)return null; if(u.pathname==='/mcp')return `${o.origin}/mcp`; const app=u.pathname.match(/^\/mcp\/apps\/([a-z][a-z0-9-]{0,57})$/); return app?`${o.origin}/mcp/apps/${app[1]}`:null; } catch{return null;} }
async function row(db:D1Database,id:string) { return db.prepare(`SELECT request_id,owner_id,agent_id,agent_label,machine_id,machine_label,resource,scopes,code_challenge,machine_proof_hash,machine_public_key,status,expires_at,result_iv,result_ciphertext,result_expires_at,redeem_attempt_id,last_poll_at,terminal_at FROM mcp_remote_auth_requests WHERE request_id=?`).bind(id).first<Row>(); }
async function expire(db:D1Database,id:string,now:number) { await db.prepare(`UPDATE mcp_remote_auth_requests SET status='expired',terminal_at=? WHERE request_id=? AND expires_at<=? AND status IN ('pending','approving','approved_awaiting_machine')`).bind(now,id,now).run(); }
function statusPage(status?:Status) { const visible=['pending','approving','approved_awaiting_machine','consumed','connected','denied','expired','cancelled','failed'].includes(status??'')?status!.replaceAll('_',' '):'not found'; return new Response(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>ProAppStore connection</title><main><h1>ProAppStore connection</h1><p>Status: ${visible}</p><p>You may return to ProAppStore.</p></main>`,{headers:{'Content-Type':'text/html; charset=utf-8',...secure()}}); }
function approvalPage(r:Row, login:string|null, ready:boolean) { const controls=ready?`<form method="post"><button>Approve connection</button></form><form method="post" action="../deny"><button>Deny</button></form>`:`<p>Sign in in a supported browser before approving.</p><p><a href="${login}">Sign in with GitHub</a> <a href="${login!.replace('provider=github','provider=google')}">Sign in with Google</a></p>`; return new Response(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Approve connection</title><main><h1>Approve connection</h1><dl><dt>Agent</dt><dd>${escape(r.agent_label)}</dd><dt>Machine</dt><dd>${escape(r.machine_label)}</dd><dt>Service</dt><dd>${escape(r.resource)}</dd><dt>Scopes</dt><dd>None</dd></dl>${controls}</main>`,{headers:{'Content-Type':'text/html; charset=utf-8',...secure()}}); }

async function mac(value:string,keyValue:string) { const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(keyValue) as BufferSource,{name:'HMAC',hash:'SHA-256'},false,['sign']); return b64(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value) as BufferSource))); }
async function makeApproval(value:Approval, env:Env) { const body=b64(new TextEncoder().encode(JSON.stringify(value))); return `${body}.${await mac(`pas:mcp:broker:approval:${body}`,env.SESSION_SIGNING_KEY)}`; }
async function approval(c:any,id:string):Promise<Approval|null> { const raw=getCookie(c,APPROVAL_COOKIE); if(!raw)return null; const dot=raw.lastIndexOf('.'); if(dot<1)return null; const body=raw.slice(0,dot); if(!timingSafeEqual(raw.slice(dot+1),await mac(`pas:mcp:broker:approval:${body}`,c.env.SESSION_SIGNING_KEY)))return null; try { const value=JSON.parse(new TextDecoder().decode(unb64(body))) as Approval; if(value.requestId!==id||value.expiresAt<=Date.now()||!(await verifySession(value.session,c.env.SESSION_SIGNING_KEY)))return null; return value; } catch{return null;} }
async function machine(c:any, verifier=false):Promise<{r:Row;proof:string;body:Record<string,unknown>}|Response> { const body=await c.req.json().catch(()=>null) as Record<string,unknown>|null; const id=body?.request_id, proof=body?.machine_proof, code=body?.code_verifier; if(!body||typeof id!=='string'||!requestIdRe.test(id)||typeof proof!=='string'||proof.length<43||proof.length>256||(verifier&&(typeof code!=='string'||code.length<43||code.length>128)))return invalid(c); const now=Date.now(); await expire(c.env.DB,id,now); const r=await row(c.env.DB,id); if(!r||!timingSafeEqual(await sha(proof),r.machine_proof_hash))return unavailable(c); if(verifier&&!timingSafeEqual(b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(code as string)))),r.code_challenge))return unavailable(c); return {r,proof,body}; }
async function seal(publicKey:string,value:unknown,id:string) { const recipient=await crypto.subtle.importKey('spki',unb64(publicKey) as BufferSource,{name:'ECDH',namedCurve:'P-256'},false,[]); const eph=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']) as CryptoKeyPair; const bits=await crypto.subtle.deriveBits({name:'ECDH',public:recipient} as unknown as SubtleCryptoDeriveKeyAlgorithm,eph.privateKey,256); const raw=await crypto.subtle.digest('SHA-256',bits); const key=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt']); const iv=crypto.getRandomValues(new Uint8Array(12)); const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(id)},key,new TextEncoder().encode(JSON.stringify(value))); const pub=await crypto.subtle.exportKey('spki',eph.publicKey) as ArrayBuffer; return {iv:b64(iv),ciphertext:JSON.stringify({ephemeral_public_key:b64(new Uint8Array(pub)),ciphertext:b64(new Uint8Array(ciphertext))})}; }
async function issue(c:any,r:Row,session:string) { if(!c.env.MCP||!c.env.INTERNAL_TOKEN||!r.machine_public_key)return false; let response:Response; try { response=await c.env.MCP.fetch('https://mcp/internal/broker/issue',{method:'POST',headers:{'Content-Type':'application/json','X-Internal-Token':c.env.INTERNAL_TOKEN},body:JSON.stringify({session,owner_id:r.owner_id,resource:r.resource,request_id:r.request_id})}); }catch{return false;} const body=await response.json().catch(()=>null) as {access_token?:unknown}|null; if(!response.ok||typeof body?.access_token!=='string')return false; let encrypted; try { encrypted=await seal(r.machine_public_key,{access_token:body.access_token,token_type:'Bearer',resource:r.resource,expires_in:86_400},r.request_id); }catch{return false;} const now=Date.now(); const updated=await c.env.DB.prepare(`UPDATE mcp_remote_auth_requests SET status='approved_awaiting_machine',approved_at=?,result_iv=?,result_ciphertext=?,result_expires_at=? WHERE request_id=? AND status='approving' AND expires_at>?`).bind(now,encrypted.iv,encrypted.ciphertext,now+RESULT_TTL,r.request_id,now).run(); return Boolean(updated.meta.changes); }

/** Called from the backend five-minute scheduler; clears all short-lived broker material. */
export async function cleanupRemoteAuthRequests(env:Pick<Env,'DB'>,now=Date.now()) { await env.DB.prepare(`UPDATE mcp_remote_auth_requests SET status='expired',terminal_at=? WHERE expires_at<=? AND status IN ('pending','approving','approved_awaiting_machine')`).bind(now,now).run(); await env.DB.prepare(`UPDATE mcp_remote_auth_requests SET status='failed',terminal_at=?,result_iv=NULL,result_ciphertext=NULL WHERE status='consumed' AND result_expires_at IS NOT NULL AND result_expires_at<=?`).bind(now,now).run(); await env.DB.prepare(`DELETE FROM mcp_remote_auth_requests WHERE terminal_at IS NOT NULL AND terminal_at<?`).bind(now-24*60*60_000).run(); }

// Old, unsafe URLs stay unavailable forever.
mcpBrokerRoutes.all(V1,withdrawn); mcpBrokerRoutes.all(`${V1}/*`,withdrawn);

mcpBrokerRoutes.post(`${PREFIX}/requests`,async c=>{ const owner=await requireUser(c); const body=await c.req.json().catch(()=>null) as Record<string,unknown>|null; const agent=body?.agent as Record<string,unknown>|undefined,machineInfo=body?.machine as Record<string,unknown>|undefined, target=resource(body?.resource,c.env.MCP_ORIGIN); if(!body||!agent||!machineInfo||!target||(body.scopes!==undefined&&(!Array.isArray(body.scopes)||body.scopes.length!==0))||typeof agent.id!=='string'||!identityRe.test(agent.id)||!printable(agent.label)||typeof machineInfo.id!=='string'||!identityRe.test(machineInfo.id)||!printable(machineInfo.label)||typeof body.code_challenge!=='string'||!challengeRe.test(body.code_challenge)||typeof body.machine_proof_hash!=='string'||!hashRe.test(body.machine_proof_hash)||typeof body.machine_public_key!=='string'||body.machine_public_key.length<80||body.machine_public_key.length>3000)return invalid(c); try{await crypto.subtle.importKey('spki',unb64(body.machine_public_key) as BufferSource,{name:'ECDH',namedCurve:'P-256'},false,[]);}catch{return invalid(c);} const now=Date.now(); let id=randomId(),ok=false; for(let i=0;i<3&&!ok;i+=1){try{ok=Boolean((await c.env.DB.prepare(`INSERT INTO mcp_remote_auth_requests (request_id,owner_id,agent_id,agent_label,machine_id,machine_label,resource,scopes,code_challenge,machine_proof_hash,machine_public_key,status,expires_at,created_at) VALUES (?,?,?,?,?,?,?,'[]',?,?,?,'pending',?,?)`).bind(id,owner.id,agent.id,printable(agent.label),machineInfo.id,printable(machineInfo.label),target,body.code_challenge,body.machine_proof_hash,body.machine_public_key,now+TTL,now).run()).meta.changes);}catch{id=randomId();}} if(!ok)return unavailable(c); const base=(c.env.APP_BASE??new URL(c.req.url).origin).replace(/\/$/,''); return c.json({protocol_version:MCP_BROKER_VERSION,request_id:id,status:'pending',expires_at:now+TTL,effective_scopes:[],approval_url:`${base}/v1${PREFIX}/requests/${id}/approve`,status_url:`${base}/v1${PREFIX}/requests/${id}/status`},201,secure()); });

mcpBrokerRoutes.get(`${PREFIX}/requests/:requestId`,async c=>{const owner=await requireUser(c),id=c.req.param('requestId');if(!requestIdRe.test(id))return unavailable(c);await expire(c.env.DB,id,Date.now());const r=await row(c.env.DB,id);if(!r||r.owner_id!==owner.id)return unavailable(c);return c.json({protocol_version:MCP_BROKER_VERSION,request_id:id,status:r.status,agent:{id:r.agent_id,label:r.agent_label},machine:{id:r.machine_id,label:r.machine_label},resource:r.resource,effective_scopes:[],expires_at:r.expires_at},200,secure());});
mcpBrokerRoutes.get(`${PREFIX}/requests/:requestId/approve`,async c=>{const id=c.req.param('requestId');if(!requestIdRe.test(id))return statusPage();await expire(c.env.DB,id,Date.now());const r=await row(c.env.DB,id);if(!r)return statusPage();const a=await approval(c,id);return approvalPage(r,a?null:`${HTTP_PREFIX}/requests/${id}/sign-in?provider=github`,Boolean(a));});
mcpBrokerRoutes.get(`${PREFIX}/requests/:requestId/sign-in`,async c=>{const id=c.req.param('requestId'),provider=c.req.query('provider');if(!requestIdRe.test(id)||(provider!=='github'&&provider!=='google'))return statusPage();await expire(c.env.DB,id,Date.now());const r=await row(c.env.DB,id);if(!r||r.status!=='pending')return statusPage(r?.status);const base=(c.env.APP_BASE??new URL(c.req.url).origin).replace(/\/$/,'');const start=new URL(`${base}/v1/auth/${provider}/start`);start.searchParams.set('return_to',`${base}/v1${PREFIX}/requests/${id}/callback`);start.searchParams.set('response_mode','broker');return c.redirect(start.toString(),302);});
mcpBrokerRoutes.get(`${PREFIX}/requests/:requestId/callback`,async c=>{const id=c.req.param('requestId'),code=getCookie(c,BROKER_LOGIN_CODE_COOKIE);deleteCookie(c,BROKER_LOGIN_CODE_COOKIE,{path:'/v1/mcp/broker/v2/',secure:true});if(!requestIdRe.test(id)||!code)return statusPage();const session=await redeemExchangeCode(c.env,code),claims=session&&await verifySession(session,c.env.SESSION_SIGNING_KEY);await expire(c.env.DB,id,Date.now());const r=await row(c.env.DB,id);if(!r||!claims||claims.uid!==r.owner_id||r.status!=='pending')return statusPage(r?.status);setCookie(c,APPROVAL_COOKIE,await makeApproval({requestId:id,session,expiresAt:Date.now()+TTL},c.env),{httpOnly:true,secure:true,sameSite:'Lax',path:'/v1/mcp/broker/v2/',maxAge:600});return c.redirect(`${HTTP_PREFIX}/requests/${id}/approve`,302);});
mcpBrokerRoutes.post(`${PREFIX}/requests/:requestId/approve`,async c=>{const id=c.req.param('requestId'),a=requestIdRe.test(id)?await approval(c,id):null;if(!a)return unavailable(c);const claims=await verifySession(a.session,c.env.SESSION_SIGNING_KEY);const now=Date.now();await expire(c.env.DB,id,now);let r=await row(c.env.DB,id);if(!r||!claims||r.owner_id!==claims.uid)return unavailable(c);if(r.status==='pending'){const claim=await c.env.DB.prepare(`UPDATE mcp_remote_auth_requests SET status='approving',approving_at=? WHERE request_id=? AND owner_id=? AND status='pending' AND expires_at>?`).bind(now,id,claims.uid,now).run();if(claim.meta.changes)r=await row(c.env.DB,id);}if(!r)return unavailable(c);if(r.status==='approved_awaiting_machine')return c.json({protocol_version:MCP_BROKER_VERSION,request_id:id,status:r.status},200,secure());if(r.status!=='approving'||!(await issue(c,r,a.session))){await c.env.DB.prepare(`UPDATE mcp_remote_auth_requests SET status='failed',terminal_at=?,failure_code='issuance_failed' WHERE request_id=? AND status='approving' AND expires_at>?`).bind(Date.now(),id,Date.now()).run();return unavailable(c);}return c.json({protocol_version:MCP_BROKER_VERSION,request_id:id,status:'approved_awaiting_machine'},200,secure());});
for(const action of ['deny','cancel'] as const)mcpBrokerRoutes.post(`${PREFIX}/requests/:requestId/${action}`,async c=>{const id=c.req.param('requestId'),a=requestIdRe.test(id)?await approval(c,id):null,claims=a&&await verifySession(a.session,c.env.SESSION_SIGNING_KEY),now=Date.now(),next=action==='deny'?'denied':'cancelled';if(!claims)return unavailable(c);const changed=await c.env.DB.prepare(`UPDATE mcp_remote_auth_requests SET status=?,terminal_at=? WHERE request_id=? AND owner_id=? AND status IN ('pending','approving','approved_awaiting_machine') AND expires_at>?`).bind(next,now,id,claims.uid,now).run();return changed.meta.changes?c.json({protocol_version:MCP_BROKER_VERSION,request_id:id,status:next},200,secure()):unavailable(c);});
mcpBrokerRoutes.post(`${PREFIX}/requests/poll`,async c=>{const value=await machine(c);if(value instanceof Response)return value;const now=Date.now(),allowed=await c.env.DB.prepare(`UPDATE mcp_remote_auth_requests SET last_poll_at=? WHERE request_id=? AND machine_proof_hash=? AND (last_poll_at IS NULL OR last_poll_at<=?)`).bind(now,value.r.request_id,value.r.machine_proof_hash,now-POLL_MS).run();if(!allowed.meta.changes)return c.json({error:'slow_down',protocol_version:MCP_BROKER_VERSION,retry_after_ms:POLL_MS},429,secure());const r=await row(c.env.DB,value.r.request_id);return r?c.json({protocol_version:MCP_BROKER_VERSION,request_id:r.request_id,status:r.status,retry_after_ms:POLL_MS,expires_at:r.expires_at},200,secure()):unavailable(c);});
mcpBrokerRoutes.post(`${PREFIX}/requests/redeem`,async c=>{const value=await machine(c,true);if(value instanceof Response)return value;const attempt=value.body.redeem_attempt_id;if(typeof attempt!=='string'||!challengeRe.test(attempt))return invalid(c);const now=Date.now();const won=await c.env.DB.prepare(`UPDATE mcp_remote_auth_requests SET status='consumed',consumed_at=?,redeem_attempt_id=? WHERE request_id=? AND status='approved_awaiting_machine' AND expires_at>? AND result_expires_at>? RETURNING request_id,result_iv,result_ciphertext,result_expires_at`).bind(now,attempt,value.r.request_id,now,now).first<Pick<Row,'request_id'|'result_iv'|'result_ciphertext'|'result_expires_at'>>();let r=won;if(!r){const current=await row(c.env.DB,value.r.request_id);if(!current||current.status!=='consumed'||current.redeem_attempt_id!==attempt||!current.result_iv||!current.result_ciphertext||!current.result_expires_at||current.result_expires_at<=now)return unavailable(c);r=current;}if(!r.result_iv||!r.result_ciphertext||!r.result_expires_at||r.result_expires_at<=now)return unavailable(c);return c.json({protocol_version:MCP_BROKER_VERSION,request_id:r.request_id,status:'consumed',credential:{iv:r.result_iv,...JSON.parse(r.result_ciphertext)}},200,secure());});
async function seen(c:any,id:string){if(!c.env.MCP||!c.env.INTERNAL_TOKEN)return false;try{const response=await c.env.MCP.fetch(`https://mcp/internal/broker/read-receipt/${encodeURIComponent(id)}`,{headers:{'X-Internal-Token':c.env.INTERNAL_TOKEN}});return response.ok&&(await response.json() as {seen?:unknown}).seen===true;}catch{return false;}}
for(const action of ['connected','failed'] as const)mcpBrokerRoutes.post(`${PREFIX}/requests/${action}`,async c=>{const value=await machine(c,true);if(value instanceof Response)return value;if(action==='connected'&&!(await seen(c,value.r.request_id)))return unavailable(c);const now=Date.now(),changed=await c.env.DB.prepare(`UPDATE mcp_remote_auth_requests SET status=?,terminal_at=?,connected_at=CASE WHEN ?='connected' THEN ? ELSE connected_at END WHERE request_id=? AND status='consumed' AND expires_at>?`).bind(action,now,action,now,value.r.request_id,now).run();return changed.meta.changes?c.json({protocol_version:MCP_BROKER_VERSION,request_id:value.r.request_id,status:action,retry_after_ms:0},200,secure()):unavailable(c);});
mcpBrokerRoutes.get(`${PREFIX}/requests/:requestId/status`,async c=>{const id=c.req.param('requestId');if(!requestIdRe.test(id))return statusPage();await expire(c.env.DB,id,Date.now());return statusPage((await row(c.env.DB,id))?.status);});
